import type { Metadata } from "next";
import { cookies } from "next/headers.js";
import * as React from "react";
import "@mui/material-pigment-css/styles.css";
import { App } from "../components/App";

import { RootProviders } from "../components/RootProviders";

export const metadata: Metadata = {
  title: "Material UI x Pigment CSS",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const { value: colorScheme = "light" } = cookieStore.get("colorScheme") ?? {};
  return (
    <html lang="en">
      <App>
        <RootProviders colorScheme={colorScheme as "light" | "dark"}>
          {children}
        </RootProviders>
      </App>
    </html>
  );
}
